messages:
  no-permission: "&cYou don't have permission to use this command."
  not-a-number: "&cPlease enter a valid number."
  success: "&aYou have received an XP bottle with &b%xp% &aXP."
  invalid-usage: "&cUsage: /bottle <levels>"
  not-enough-levels: "&cYou don't have enough levels!"
item:
  name: "&6XP Bottle"
  lore:
    - "&7Contains experience equivalent"
    - "&7to &b%xp% &7XP."
  model-data: 0
  color: "00FF00"